const { Router } = require('express')
const { routerAuth } = require('./auth/auth')
const { notFound } = require('../controller')
const { routerCopy } = require('./server/copy')
const { routerAdmin } = require('./admin/admin')
const { routerSocket } = require('./server/socket')
const { routerNotification } = require('./log/notification')
const { routerFolder } = require('./poll server/folder')
const { routerChannel } = require('./poll server/channel')
const { routerMeter } = require('./poll server/meter')
const { routerUSPD } = require('./poll server/uspd')
const { routerJournal } = require('./log/journal')
const { routerSchema } = require('./poll server/schema')

module.exports.router = Router()
    .use('/*', (req, res, next) => {
        console.log(req.originalUrl, req.method)
        next()
    })
    .use('/admin', routerAdmin)
    .use('/auth', routerAuth)
    .use('/copy', routerCopy)
    .use('/socket', routerSocket)
    .use('/notification', routerNotification)
    .use('/folder', routerFolder)
    .use('/channel', routerChannel)
    .use('/meter', routerMeter)
    .use('/uspd', routerUSPD)
    .use('/journal', routerJournal)
    .use('/schema', routerSchema)
    .use('/*', notFound)
