const { Router } = require('express')
const { checkToken } = require('../../middleware/token')
const { createAdmin, activateAdmin, removeAdmin, updateAdmin, findAdmins, findOneAdmin, sessionDelete, createSuperAdmin, updateProfile, superAdminDelete } = require('../../controller/admin/admin')

module.exports.routerAdmin = Router()
    .get('/all', checkToken(), findAdmins)
    .get('/one/:id', checkToken(), findOneAdmin)
    .post('/create', checkToken(), createAdmin)
    .post('/create-admin', createSuperAdmin)
    .patch('/update-profile', checkToken(), updateProfile)
    .patch('/update/:id', checkToken(), updateAdmin)
    .put('/activate/:id', checkToken(), activateAdmin)
    .delete('/reactivate/:id', checkToken(), removeAdmin)
    .delete('/session-remove/:id', checkToken(), sessionDelete)
    .delete('/reset', checkToken(), superAdminDelete)